version: "3"

services:

  app:
    build: .
    env_file:
      - .env
    image: cloudolife/ssr-prerender:latest
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis